---
version: "2.1"
services:
  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      - UMASK_SET=022
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt:/mnt
      - /mnt/n0tDocker/n0tArr/Bazarr:/config
    ports:
      - 6767:6767/tcp
  radarr:
    image: hotio/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - /mnt/n0tDocker/n0tArr/Radarr:/config
      - /mnt:/mnt
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022
    volumes:
      - /mnt/:/mnt/
      - /mnt/n0tDocker/n0tArr/Sonarr/:/config # Bazarr data
    ports:
      - 8989:8989
    restart: unless-stopped
  readarr:
    image: hotio/readarr:unstable
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022
    volumes:
      - /mnt/:/mnt/ # Location of your movies
      - /mnt/n0tDocker/n0tArr/Readarr/:/config
    ports:
      - 8989:8989
    restart: unless-stopped
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022
    volumes:
      - /mnt/:/mnt/
      - /mnt/n0tDocker/n0tArr/Lidarr/:/config
    ports:
      - 8686:8686
    restart: unless-stopped
